# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 18:28
import os

from django.db import migrations

from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), './fixtures'))
fixture_filename = 'initial_data.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("users", "User")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170605_1631'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
